import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { ColorSchemeScript, createTheme, mantineHtmlProps, MantineProvider } from "@mantine/core";
import "./globals.css";
import "@mantine/core/styles.css";
import { ToastContainer } from "react-toastify";
import Navbar from "../components/Navbar";
import { UserProvider } from "../context/UserContext";
import { Suspense } from "react";

const getRaleway = Raleway({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-raleway",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  primaryColor: "violet",
  black: "#000",
  white: "#fff",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <MantineProvider theme={theme} defaultColorScheme="dark">
        <head>
          <ColorSchemeScript />
        </head>
        <body style={{ fontFamily: getRaleway.style.fontFamily }} className="antialiased">
          <UserProvider>
            <ToastContainer theme="colored" />
            <Navbar />
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </UserProvider>
        </body>
      </MantineProvider>
    </html>
  );
}
